version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        update-types:
          - minor
          - patch
    # airtable/blocks only supports v17
    ignore:
      - dependency-name: react
        versions: ["^18"]
